version: '2'
services:
  kmptdemo-app:
    image: kmptdemo
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:postgresql://kmptdemo-postgresql:5432/kmptDemo
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
    ports:
      - 8040:8040
  kmptdemo-postgresql:
    extends:
      file: postgresql.yml
      service: kmptdemo-postgresql
